config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :charges
  resources :dues, only: [:index, :show] do
    resources :enrollments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/due.rb
class Due < ApplicationRecord

  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :amount, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :status, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :due
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enrollments
  has_many :enrolled_dues, through: :enrollments, source: :due
  include Humanizer
  require_human_on :create
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(due)
    return enrolled_dues.include?(due)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :humanizer_answer, :humanizer_question_id])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def new
  end

  def create
  end
end

app/controllers/dues_controller.rb
class DuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @dues = Due.all
  end

  def new
    @due = Due.new
  end

  def create
    @due = current_user.dues.create(course_params)
  end

  def show
    @due = Due.find(params[:id])
  end

  private

  def due_params
    params.require(:due).permit(:description, :title, :amount, :status)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.enrollments.create(due: current_due)

    # Amount in cents
    @amount = (current_due.amount * 100).to_i

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Beta Omega Chapter Dues',
      currency: 'usd',
    })

  redirect_to due_path(current_due)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_due
    @current_due ||= Due.find(params[:due_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/dues/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">

  <% @dues.each do |due| %>
    <h2 class="text-center"><%= due.title %></h2>
    <div>
      <%= link_to 'More Details', due_path(due), class: 'btn btn-primary btn-large' %>
    </div>
    <br class="clr" />
  <% end %>
</div>

app/views/dues/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <br />
  <br />
  <h1 class="text-center"><%= @due.title %></h1>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
      <%= number_to_currency @due.amount %>
      </span>
    </div>
    <div class="col-sm-4 col-12">
      <%= @due.description %>
    </div>
      <br />
      <br />
      <% if current_user && current_user.enrolled_in?(@due) %>
      <div style="margin: auto">
        <h3 class="badge badge-info">You Are Financial!</h3>
      </div>
      <% else %>
      <div style="margin: auto">
        <h3 class="badge badge-info">You Are NOT Financial!</h3>
      </div>
        <div style="margin: auto">
          <%= form_tag due_enrollments_path(@due) do %>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-email="<%= current_user.email %>"
                    data-description="<%= @due.title %> (<%= number_to_currency @due.amount %>)"
                    data-amount="<%= (@due.amount * 100).to_i %>"
                    data-locale="auto"></script>
          <% end %>
        </div>
      <% end %>
  </div>
    <br />
    <br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DC Iotas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="#navbarNavAltMarkup">
      <span class="navbar-toggler-icon"></span>
    </button>
      <nav class="navbar">
        <%= link_to root_path do %>
          <%= image_tag "dciotas1.jpg", width: "30", height: "30", class: 'd-inline-block align-top', alt: '' %>
        <% end %>
      </nav>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
          <a class="nav-item nav-link">
            <%= link_to 'Pay Chapter Dues', dues_path, class: 'nav-link' %>
          </a>
        <% if user_signed_in? %>
          <a class="nav-item nav-link">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </a>
        <% else %>
          <a class="nav-item nav-link">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </a>
          <a class="nav-item nav-link">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </a>
        <% end %>
      </div>
    </div>
  </nav>


  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>

  <div style="margin: auto">
    <%= image_tag "dciotas1.jpg", class: 'logo-image'  %>
  </div>

  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col">
        <b>Contact</b>
        <br />
        <%= mail_to 'iptbetaomega.secretary@gmail.com', "Email Us" %>
        <br />
        PO Box 55691
        <br />
        Washington DC, 20040
        </div>

        <div class="social">
          <b>Social</b>
          <br />
          <br />
          <%= link_to 'https://www.facebook.com/iptbetaomega/' do %>
          <span class="fa fa-facebook fa-2x social-button"></span>
          <% end %>
          <%= link_to 'https://www.twitter.com/iptbetaomega' do %>
          <span class="fa fa-twitter fa-2x social-button"></span>
          <% end %>
          <%= link_to 'https://www.instagram.com/thedciotas' do %>
          <span class="fa fa-instagram fa-2x social-button"></span>
          <% end %>
        </div>


      </div>
    </div>
  </div>


  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<html>
  <head>
      <title>DC Iotas</title>
  </head>
  <body>

    <div class="hero">
      <br />
      <div class="frosty col-10 offset-1 text-center">
      <br />
      </div>
    </div>

<p />
<p />
<h3 style="text-align:center;white-space:pre-wrap;">The DC Iotas!</h3>
<p />
<p class="maintext">Welcome to the website of the Beta Omega Alumni Chapter of Iota Phi Theta Fraternity Inc.
  We are pleased you decided to stop by and check us out. We have been operating here in the Washington, DC metropolitan area since 1970 and we plan to still be here working it out on September 19, 2063.

  Over the last 40 years, we have forged some key friendships and partnerships with other organizations and like-minded individuals who share our passion for service. One of the hallmarks of our existence has been our dedicated service to improving the lives of young people one program and one child at a time. We have run youth mentoring programs in Ward 8 for more than 15 years and look forward each year to identifying new young people and new service goals as we work to be good neighbors.

  In 2009, we have expanded our service initiatives to include a Developing Better Fathers Program. Through a grant from DC Department of Human Services we are providing case management to 20 fathers who are seeking to improve their relationships with their children. The program includes support and wrap around services to include job training and placement, counseling on improving economic stability, and dealing with and preventing domestic violence.

  If you have the desire to get involved and help make a positive difference in the lives of young people, we would welcome the opportunity to meet with you to discuss how your skills best use to help improve the negative socio-economic conditions that plague our community’s most deserving citizens.</p>

<hr />

<div class="container">
  <div class="row">
    <div class="col">
      <h2>History</h2>
      <p class="maintext">The Beta Omega Alumni Chapter (BOAC) is the second oldest alumni chapter of Iota Phi Theta Fraternity, Inc. chartered in Washington, D.C. on September 19, 1970. Ten brothers who were recent college graduates established Beta Omega with a vision to spread the principles of Iota and the commitment to public service and making an impact in all aspects of the human endeavor.
        <ul>
          <li>Edgar Johnson - Alpha Chapter - Polaris</li>
          <li>Kenneth Smith* - Beta Chapter - Vice-Polaris</li>
          <li>Arthur Wyatt - Beta Chapter - Secretary</li>
          <li>Michael Parker - Beta Chapter - Treasurer</li>
          <li>Lamont Bland* - Alpha Chapter - Historian</li>
          <li>Malcolm Daniels - Beta Chapter</li>
          <li>Daniel Morgan - Beta Chapter</li>
          <li>Algernon Tucker - Beta Chapter</li>
          <li>Melvin Watkins - Beta Chapter</li>
          <li>Edward Whiting - Beta Chapter</li>
        </ul>
      * <i>Alpha Iota Omega Memorial Chapter</i>
      </p>
    </div>
  </div>
</div>

<hr />

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Chartered Chapters</h2>
      <p class="maintext">The Beta Omega Alumni Chapter has made insurmountable efforts over the years to charter and establish a working relationship with undergraduate chapters in the Washington D.C. metropolitan area. The undergraduate chapters we have helped charter are:
      <ul>
        <li>Theta - University of the District of Columbia (formerly Federal City College)</li>
        <li>Mu - Bowie State University</li>
        <li>Nu - University of Maryland, College Park</li>
        <li>Alpha Tau - Howard University</li>
      </ul></p>
    </div>
  </div>
</div>

<hr />

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Executive Board</h2>
        <ul>
          <li>Polaris - Jamel Walker</li>
          <li>Vice Polaris - James White</li>
          <li>Treasurer - Kareem Byrd</li>
          <li>Secretary - Rickey Davis</li>
        </ul>
    </div>
  </div>
</div>

<hr />

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Beta Omega Social Services</h2>
      <p class="maintext">In 2003, the Beta Omega Alumni Chapter established Beta Omega Social Services, Inc. (BOSS). BOSS is the non-profit philanthropic arm of the chapter and with a mission to foster the socio-economic enrichment and advance the development of opportunities for underserved communities in the Greater Washington D.C. area through social service. Current BOSS projects include mentoring programs, educational programs, health awareness, and scholarship programs for youth.

      One of our most dedicated brothers Michael Gilbert died after a long illness in 1995. Michael was a single parent for several years, and raised his daughter Lauren from infancy. Beta Omega started the Michael Gilbert Scholarship Fund in 1996 and the first recipient was his daughter, Lauren Gilbert. The Beta Omega Alumni Chapter granted her $2,500 to attend the University of Tampa. In 2004, the program transferred to BOSS in the effort to establish an endowment fund to raise more money to fund this program.

      The Beta Omega Alumni Chapter along with several individuals from the chapter have been recognized by the fraternity for their contributions including: Tony Watson Award – Alumni Brother of the Year recipients, two former Grand Polari, and the chapter’s efforts were recognized again with 2001 – 2003 Alumni Chapter of the Year Award. The chapter hosted the 10th National Conclave in 1983 and the 24th National Conclave in 1994.</p>
    </div>
  </div>
</div>

<hr />

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Beta Omega Initiates</h2>
      <p class="maintext">Dennis Carraway - Joseph Johnson - Lenny Richeson - Tom Payne - Marvin Parker - Edward Ball - James Walls - Vincent E. Parker - Marquis Smith - Bobby Timberlake - Romell K. Short - Issac July - Akil Brown - Ernest Walker - Gregory Lawrence - Anthony Allen - Eric Hollins - Kareem Byrd - Calvin Hicks - Cedric Flynt - Steven Lee - William Murry - Kelvin Coachman - Shawn Williams - Alton Ward - Timothy Fenner - Brandon Smith - Jonathan Harrison - Darroll Screen</p>
    </div>
  </div>
</div>

<hr />

<h2>Chapter Calendar</h2>

<br />
<div class="calendar">
  <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=aXB0YmV0YW9tZWdhLnNlY3JldGFyeUBnbWFpbC5jb20&amp;src=YWRkcmVzc2Jvb2sjY29udGFjdHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%2322AA99&amp;color=%23329262&amp;color=%231F753C" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>

<br />

<hr />

</body>